<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class DataSatuanSeeder extends Seeder
{
    public function run(): void
    {
        $now = now();

        $data = [
            'Alat',
            'Ampul',
            'Baduta',
            'Balita',
            'Baru',
            'Batang',
            'Batang Pohon',
            'Bidang',
            'Biji',
            'Bks',
            'Botol',
            'Botol / 100',
            'Botol / 1000',
            'Botol / 7 Caps',
            'Box',
            'Box / 100',
            'Box / 20',
            'Box / 30',
            'Btp',
            'Buah',
            'Buku',
            'Bulan',
            'Byte',
            'Cm',
            'Desa',
            'Dos',
            'Dos / 10 Vial',
            'Dos / 100 Tablet',
            'Dos / 5',
            'Dos / 50',
            'Dosis',
            'Doz',
            'Drum',
            'Dsn',
            'Dus',
            'Ekor',
            'Eksemplar',
            'Eksemplar / Buku',
            'Flacon',
            'Fls',
            'Fokus',
            'Galon',
            'Gelas',
            'Gram',
            'Group',
            'Ha',
            'Hari',
            'Hari / M2',
            'Ijin',
            'Ikat',
            'Institusi',
            'Jam',
            'Jenis',
            'Jerigen',
            'Kaleng',
            'Kaleng/1000 Tablet',
            'Kali',
            'Kaplet',
            'Kapsul',
            'Kartu',
            'Kasus',
            'Kecamatan',
            'Kegiatan',
            'Kelurahan',
            'Kendaraan',
            'Keranjang',
            'Kg',
            'Kg / Powder',
            'Kit',
            'KK',
            'Km',
            'Kotak',
            'Kpg',
            'Ktg',
            'Kwh',
            'Lembaga',
            'Lembar',
            'Liter',
            'Log',
            'Lokasi',
            'Lot',
            'Ls',
            'Ltr',
            'Luas / M2',
            'Lusin',
            'M',
            'M / Lari',
            'M1',
            'M2',
            'M2 Kedalaman S.D 1 M',
            'M2 Per Bulan',
            'M2 Per Hari',
            'M2/Tahun',
            'M3',
            'Macam',
            'Materi',
            'Media',
            'Menit',
            'Meter',
            'Minggu',
            'Ml',
            'MMKolom',
            'Ons',
            'Orang',
            'Orang / Acara',
            'Orang / Alamat',
            'Orang / Bulan',
            'Orang / Bulan / Kegiatan',
            'Orang / Hari',
            'Orang / Jam',
            'Orang / Jam / Pelajaran',
            'Orang / Kali',
            'Orang / Kamar',
            'Orang / Kedatangan',
            'Orang / Keg. / Bln',
            'Orang / Kegiatan',
            'Orang / Materi',
            'Orang / Paket / Pekerjaan',
            'Orang / Perjalanan',
            'Orang / PP',
            'Orang / Sessi',
            'Orang / Session',
            'Orang / Titik',
            'Organisasi',
            'Pack',
            'Pail',
            'Paket',
            'Parpol',
            'Pasang',
            'Pc',
            'Pcs',
            'Pekerjaan',
            'Pelepah',
            'Pendampingan',
            'Per 100 Lembar',
            'Per Balok',
            'Per Batang',
            'Per Batang Pohon',
            'Per Buku',
            'Per Bulan',
            'Per Bungkus',
            'Per Detik',
            'Per Keping',
            'Per Kotak',
            'Per Liputan',
            'Per Orang',
            'Per Rim',
            'Per Ruang',
            'Per Sampel',
            'Per Tayang',
            'Per Titik',
            'Persen',
            'Pert 100 Buah',
            'Pick Up',
            'Porsi',
            'Posyandu',
            'Pot',
            'Produk Hukum',
            'Pulsa',
            'Rean',
            'Regu',
            'Rim',
            'Roll',
            'Roll Besar',
            'Rupiah',
            'Tes',
            '%',
            'Paku',
            'RW',
            'Sachet',
            'Sampel',
            'Sekolah',
            'Semester',
            'Sesi',
            'Set',
            'Shift',
            'Siklus',
            'Siswa',
            'Stel',
            'Strip',
            'Surat',
            'Tablet',
            'Tabung',
            'Tahun',
            'Tangki (4000 Liter)',
            'Tayang / Spot',
            'Tayang / Spot Durasi 30 Detik',
            'Tempat',
            'Titik',
            'Titik Lampu',
            'Ton',
            'Triwulan',
            'Tube',
            'Unit',
            'Unit / Bulan',
            'Unit / Pompa',
            'Unit / Tahun',
            'USK',
            'VA',
            'Vial',
            'Watt',
            'Zak',
            'Stek',
            'Pols',
            'Orang / Tahun',
            'Orang / Paket',
            'Orang / Responden',
            'Orang / Terbitan',
            'Orang / Jam Pelajaran',
            'm3',
            'Butir',
            'Siswa / Mata Ujian',
            'Naskah / Pelajaran',
            'Per Butir Soal',
            'Per Modul',
            'Per Halaman',
            'Dokumen',
            'Kapsul/Tablet/Kaplet',
            'Anakan',
            'Per Tumpuk',
            'Per Karung',
            'Per Sisir',
            'Exemplar',
            'Keping',
            'pp',
            'Per Hari',
            'Arsip',
            'Asosiasi dan Serikat Pekerja',
            'Badan Usaha',
            'Bahasa',
            'Beasiswa',
            'Bendung',
            'Bendungan',
            'Berita Acara',
            'Berkas',
            'Biaya',
            'BPSK',
            'Daftar',
            'DI',
            'Dokumen Ketetapan',
            'Dokumen SSPD',
            'Dokumen Surat Persetujuan/Penolakan',
            'Domain',
            'Entitas',
            'Entry',
            'Gampong',
            'Hektar',
            'Kab/Kota',
            'Kabupaten/Kota',
            'Kampung',
            'Kamus',
            'Kawasan',
            'Kawasan Transmigrasi',
            'Kegiatan usaha',
            'Kelompok',
            'Kelompok Masyarakat',
            'Keluarga',
            'Kepala Keluarga',
            'Kerja Sama',
            'Kesepakatan',
            'Komoditi',
            'Konten Digital',
            'Lembaga Kemasyarakatan',
            'Lembaga Masyarakat',
            'Liter/Detik',
            'Lokus',
            'LPK',
            'LPKSM',
            'M³/Hari',
            'Makam',
            'Naskah',
            'Objek',
            'Obyek Pajak',
            'Operasi',
            'Pelabuhan Perikanan',
            'Pelaku Ekonomi',
            'Pelaku Usaha',
            'Pelatda',
            'Penerbit',
            'Pengaduan',
            'Pengelola',
            'Pengguna',
            'Penyelenggara SPAM',
            'Perangkat Daerah',
            'Perizinan',
            'Perkara',
            'Permohonan',
            'Perpustakaan',
            'Perusahaan',
            'Peserta didik',
            'Peserta Didik',
            'Pokmas / Ormas',
            'Produk',
            'Publikasi',
            'Rekomendasi',
            'Rumah Tangga',
            'Sarana',
            'Sarana dan Prasarana',
            'Satuan Pendidikan',
            'Satuan Pendidikan Tinggi',
            'Satuan Permukiman',
            'Sertifikat',
            'Sistem Jaringan',
            'SOP',
            'SR',
            'Surat Keputusan',
            'Tatanan',
            'UMKM',
            'Unit Kerja',
            'Unit Managemen',
            'Unit Rumah',
            'Unit Usaha',
            'Usulan',
            'Varietas',
            'Varietas Unggul Baru (VUB)',
            'VUB',
            'Boks',
            'Orang / Semester',
            'Orang / Triwulan',
            'Laporan',
            'Supp',
            'Inch',
            'Orang/Paket',
            'Ekpl',
            'OH',
            'OB',
            'Gross',
            'karton',
            'rt',
            'Orang / Flight',
            'OT',
            'Ruang',
            'OK',
            'Orang Kegiatan',
            'Orang/Kali',
            'Bh',
            'Unit/Tahun',
            'ktk 10 x 10 tab',
            'ktk 30 amp',
            'ktk 10 vial',
            'botol 60 ml',
            'btl 60 ml',
            'botol 10 ml',
            'kaleng 1000',
            'ktk 24',
            'ktk 100 ampul',
            'ktk 30 ampul',
            'ktk 480 tab',
            'ktk 30 tab',
            'ktk 25 tube',
            'ktk25 tube',
            'btl 1000 tab',
            'SAK',
            'OJ',
            'OP',
            'KOTAK 24 PCS',
            'KOTAK 36 PCS',
            'KOTAK 100',
            'KOTAK 101',
            'KOTAK 50 PASANG',
            'KOTAK 50',
            'ROL',
            'BOTOL 25 TEST',
            'BOTOL 10 TEST',
            'TEST',
            'GULUNG',
            'botol 500 ml',
            'ktk 50 tablet',
            'ktk 5 x 10 tab',
            'btl 100 tab',
            'btl 250 tab',
            'botol 250 ml',
            'ktk 20 amp',
            'btl 15 ml',
            'kaleng 250',
            'ktk 10 amp',
            'ktk 24 pot',
            'ktk 2 x 10 supp',
            'Krt',
            'TUMPUK',
            'Orter',
            '40 PK',
            'rtng',
            'ppn',
            'Helicopter',
            '500 Gr / klg',
            '20 Gr / bks',
            '250 Ml',
            '1 Kg',
            '1 Liter',
            '40 Wat',
            'Mobil',
            'Pak',
        ];

        $insert = [];
        foreach ($data as $nama) {
            $insert[] = [
                'nama_satuan' => $nama,
                'created_at' => $now,
                'updated_at' => $now,
            ];
        }

        DB::table('data_satuan')->insert($insert);
    }
}
